package com.m16a4666.heywear.utils

object EmojiUtil {

    //
    fun getUrl(key: String): String? {
        return map[key]
    }

    //小黑盒表情映射表（你可能要自己更新了）
    val map = mapOf(
        //Cube系列
        "cube_来财" to "https://imgheybox.max-c.com/heybox/emoji/cube_142.png",
        "cube_我方了" to "https://imgheybox.max-c.com/heybox/emoji/cube_143.png",
        "cube_时间旅者" to "https://imgheybox.max-c.com/heybox/emoji/cube_141.png",
        "cube_猛男微笑" to "https://imgheybox.max-c.com/heybox/emoji/cube_136.png",
        "cube_剑星涂鸦" to "https://imgheybox.max-c.com/heybox/emoji/cube_135.png",
        "cube_剑星伊芙" to "https://imgheybox.max-c.com/heybox/emoji/cube_133.png",
        "cube_悟空" to "https://imgheybox.max-c.com/heybox/emoji/cube_105.png",
        "cube_吃鸡啦" to "https://imgheybox.max-c.com/heybox/emoji/cube_115.png",
        "cube_鸡毙你" to "https://imgheybox.max-c.com/heybox/emoji/cube_116.png",
        "cube_毁灭战士" to "https://imgheybox.max-c.com/heybox/emoji/cube_131.png",
        "cube_P的谎言" to "https://imgheybox.max-c.com/heybox/emoji/cube_132.png",
        "cube_良民" to "https://imgheybox.max-c.com/heybox/emoji/cube_111.png",
        "cube_浪人砍一刀" to "https://imgheybox.max-c.com/heybox/emoji/cube_114.png",
        "cube_嬉水女王" to "https://imgheybox.max-c.com/heybox/emoji/cube_112.png",
        "cube_欧润吉" to "https://imgheybox.max-c.com/heybox/emoji/cube_134.png",
        "cube_摸摸头" to "https://imgheybox.max-c.com/heybox/emoji/cube_102.png",
        "cube_电牛" to "https://imgheybox.max-c.com/heybox/emoji/cube_103.png",
        "cube_摘墨镜" to "https://imgheybox.max-c.com/heybox/emoji/cube_104.png",
        "cube_窝囊" to "https://imgheybox.max-c.com/heybox/emoji/cube_101.png",
        "cube_小鸡" to "https://imgheybox.max-c.com/heybox/emoji/cube_96.png",
        "cube_僵尸" to "https://imgheybox.max-c.com/heybox/emoji/cube_95.png",
        "cube_2025" to "https://imgheybox.max-c.com/heybox/emoji/cube_113.png",
        "cube_doge" to "https://imgheybox.max-c.com/heybox/emoji/cube_13.png",
        "cube_滑稽" to "https://imgheybox.max-c.com/heybox/emoji/cube_34.png",
        "cube_感动" to "https://imgheybox.max-c.com/heybox/emoji/cube_24.png",
        "cube_微笑" to "https://imgheybox.max-c.com/heybox/emoji/cube_62.png",
        "cube_乖" to "https://imgheybox.max-c.com/heybox/emoji/cube_31.png",
        "cube_打脸" to "https://imgheybox.max-c.com/heybox/emoji/cube_51.png",
        "cube_闭嘴" to "https://imgheybox.max-c.com/heybox/emoji/cube_55.png",
        "cube_晕" to "https://imgheybox.max-c.com/heybox/emoji/cube_23.png",
        "cube_笑cry" to "https://imgheybox.max-c.com/heybox/emoji/cube_32.png",
        "cube_喜欢" to "https://imgheybox.max-c.com/heybox/emoji/cube_14.png",
        "cube_捂脸哭" to "https://imgheybox.max-c.com/heybox/emoji/cube_22.png",
        "cube_惊讶" to "https://imgheybox.max-c.com/heybox/emoji/cube_16.png",
        "cube_开心" to "https://imgheybox.max-c.com/heybox/emoji/cube_21.png",
        "cube_哭泣" to "https://imgheybox.max-c.com/heybox/emoji/cube_11.png",
        "cube_酷" to "https://imgheybox.max-c.com/heybox/emoji/cube_12.png",
        "cube_困" to "https://imgheybox.max-c.com/heybox/emoji/cube_54.png",
        "cube_喷水" to "https://imgheybox.max-c.com/heybox/emoji/cube_46.png",
        "cube_赞" to "https://imgheybox.max-c.com/heybox/emoji/cube_41.png",
        "cube_学习" to "https://imgheybox.max-c.com/heybox/emoji/cube_42.png",
        "cube_生气" to "https://imgheybox.max-c.com/heybox/emoji/cube_53.png",
        "cube_睡觉" to "https://imgheybox.max-c.com/heybox/emoji/cube_66.png",
        "cube_叹气" to "https://imgheybox.max-c.com/heybox/emoji/cube_43.png",
        "cube_摊手" to "https://imgheybox.max-c.com/heybox/emoji/cube_45.png",
        "cube_吐" to "https://imgheybox.max-c.com/heybox/emoji/cube_56.png",
        "cube_哇" to "https://imgheybox.max-c.com/heybox/emoji/cube_63.png",
        "cube_并不简单" to "https://imgheybox.max-c.com/heybox/emoji/cube_26.png",
        "cube_委屈" to "https://imgheybox.max-c.com/heybox/emoji/cube_25.png",
        "cube_加油" to "https://imgheybox.max-c.com/heybox/emoji/cube_44.png",
        "cube_凄凉" to "https://imgheybox.max-c.com/heybox/emoji/cube_36.png",
        "cube_沧桑" to "https://imgheybox.max-c.com/heybox/emoji/cube_35.png",
        "cube_吓" to "https://imgheybox.max-c.com/heybox/emoji/cube_65.png",
        "cube_咕咕" to "https://imgheybox.max-c.com/heybox/emoji/cube_61.png",
        "cube_黑人问号" to "https://imgheybox.max-c.com/heybox/emoji/cube_15.png",
        "cube_怒" to "https://imgheybox.max-c.com/heybox/emoji/cube_33.png",
        "cube_汗" to "https://imgheybox.max-c.com/heybox/emoji/cube_64.png",
        "cube_打咩" to "https://imgheybox.max-c.com/heybox/emoji/cube_93.png",
        "cube_上学-丧" to "https://imgheybox.max-c.com/heybox/emoji/cube_92.png",
        "cube_上学-乐" to "https://imgheybox.max-c.com/heybox/emoji/cube_91.png",
        "cube_这是什么鸟" to "https://imgheybox.max-c.com/heybox/emoji/cube_86.png",
        "cube_庆祝" to "https://imgheybox.max-c.com/heybox/emoji/cube_73.png",
        "cube_圣诞树" to "https://imgheybox.max-c.com/heybox/emoji/cube_72.png",
        "cube_H币" to "https://imgheybox.max-c.com/heybox/emoji/cube_52.png",
        "cube_我懂你" to "https://imgheybox.max-c.com/heybox/emoji/cube_76.png",
        "cube_阳" to "https://imgheybox.max-c.com/heybox/emoji/cube_81.png",
        "cube_比心" to "https://imgheybox.max-c.com/heybox/emoji/cube_82.png",
        "cube_wota" to "https://imgheybox.max-c.com/heybox/emoji/cube_83.png",
        "cube_鹅" to "https://imgheybox.max-c.com/heybox/emoji/cube_84.png",
        "cube_握草" to "https://imgheybox.max-c.com/heybox/emoji/cube_85.png",
        "cube_超人" to "https://imgheybox.max-c.com/heybox/emoji/cube_94.png",
        "cube_庆祝-圣诞" to "https://imgheybox.max-c.com/heybox/emoji/cube_74.png",
        "cube_你懂我" to "https://imgheybox.max-c.com/heybox/emoji/cube_75.png",
        "cube_2023" to "https://imgheybox.max-c.com/heybox/emoji/cube_71.png",
        "cube_2024" to "https://imgheybox.max-c.com/heybox/emoji/cube_106.png",
        "cube_吹口哨" to "https://imgheybox.max-c.com/heybox/emoji/cube_123.png",
        "cube_太酷啦" to "https://imgheybox.max-c.com/heybox/emoji/cube_125.png",
        "cube_蛋糕" to "https://imgheybox.max-c.com/heybox/emoji/cube_126.png",

        //盒娘系列 
        "heygirl_白嫖怪" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_13.png",
        "heygirl_敲开心" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_34.png",
        "heygirl_这…" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_33.png",
        "heygirl_无语" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_32.png",
        "heygirl_茄化" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_31.png",
        "heygirl_痴" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_15.png",
        "heygirl_惊" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_44.png",
        "heygirl_记下来" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_45.png",
        "heygirl_挨刀" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_46.png",
        "heygirl_偷看" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_42.png",
        "heygirl_开可乐" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_35.png",
        "heygirl_滑稽" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_41.png",
        "heygirl_哈哈" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_36.png",
        "heygirl_喝奶茶" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_43.png",
        "heygirl_疑问" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_14.png",
        "heygirl_耶嘿" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_11.png",
        "heygirl_哭" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_12.png",
        "heygirl_害羞" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_22.png",
        "heygirl_捏脸" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_21.png",
        "heygirl_喜欢" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_16.png",
        "heygirl_吃瓜" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_26.png",
        "heygirl_rua!" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_25.png",
        "heygirl_秀" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_24.png",
        "heygirl_苦酒入喉" to "https://imgheybox.max-c.com/heybox/emoji/heygirl_23.png"
    )
}